sudo: required

language: cpp

os:
  - linux
  - osx

compiler:
  - clang++
  - g++

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
    else
      brew update;
    fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get -qq install gcc-4.9 g++-4.9;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90;
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90;
      wget http://ftp.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz;
      tar xf lcov_1.11.orig.tar.gz;
      sudo make -C lcov-1.11/ install;
    else
      brew tap homebrew/versions;
      brew install llvm --with-clang --with-asan;
      brew install gcc49;
      alias gcc=/usr/bin/g++-4.9;
      alias gcov=/usr/bin/gcov-4.9;
      brew install lcov;
    fi
  - gem install coveralls-lcov;
  - g++ --version;
  - clang++ --version;
  - lcov --version;

before_script:
  - git submodule update --init --recursive

script:
  - make check

after_success:
  - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN coverage/test/test.info
env:
  global:
    secure: XqkgUBJlgGELxQy3z49m6gF5PohLpeEBZE/HfZRbHePM0MAEP6RysIxLf3pDXSy8zpWD4L4TYjdyxww2eBeuxj7vWBKPv+nKxNz+NUWg8LA0oY5Di9g+yxL9Jt4tUahfeFR7xnzTM5d3BQBuavA0iTG2v6+Jv8P+lpnBDMZUKcmTzMK9rwhyMeFn4F1F7Hnzn31lOiH0dB7jhIA7FhALjsqan3YODsW9djwZ5MHrETOtCNTIvm5aLWOGpgLi1jTXXD/TojgJqc0x6EhB+T/86D8kzSkKmbi2jRzWYa+ai0LncDyXgg3QI2LFAgX9XR6IJWi2wMCfEifmWVzfucWOK5jMuVlS4Fa2BcRjBpRwNZ35bBNZkdtiDQ4R4j5Mi9omxBdww1ka0shwDDTfXx8LHY4dtVqrpd43l0QRljAblPQFxYTrqcMFZqpgmEjyLUQo2SwxXeDf6yGinffsxqGxCXUMLWfnpa/a3dUr59olZXU+Sn/xNtQomwdCofMocTF18SVxbhrS2Qx0HrfOPrd+3EgsueVsJPMltSAv6ro82wrQLyHyDH59nFqxUbIdg1AxuT8N0xZZRzEfcCWteueME4Uwe/iV4IiWQSskPxieNqGyUnJsVRvOGf9xGzUMXXgLznppLi0VfdqvyrQlqeOO6H7LWSVEPj8cDlJW/Iw8VUI=
